138a139,165
> # Experimental parameter to specify the maximum number of events a node will
> # buffer, per subscription, before returning an error and closing the
> # subscription. Must be set to at least 100, but higher values will accommodate
> # higher event throughput rates (and will use more memory).
> experimental_subscription_buffer_size = 200
> 
> # Experimental parameter to specify the maximum number of RPC responses that
> # can be buffered per WebSocket client. If clients cannot read from the
> # WebSocket endpoint fast enough, they will be disconnected, so increasing this
> # parameter may reduce the chances of them being disconnected (but will cause
> # the node to use more memory).
> #
> # Must be at least the same as "experimental_subscription_buffer_size",
> # otherwise connections could be dropped unnecessarily. This value should
> # ideally be somewhat higher than "experimental_subscription_buffer_size" to
> # accommodate non-subscription-related RPC responses.
> experimental_websocket_write_buffer_size = 200
> 
> # If a WebSocket client cannot read fast enough, at present we may
> # silently drop events instead of generating an error or disconnecting the
> # client.
> #
> # Enabling this experimental parameter will cause the WebSocket connection to
> # be closed instead if it cannot read fast enough, allowing for greater
> # predictability in subscription behaviour.
> experimental_close_on_slow_client = false
> 
247a275,279
> # Mempool version to use:
> #   1) "v0" - (default) FIFO mempool.
> #   2) "v1" - prioritized mempool.
> version = "v0"
> 
276a309,324
> # ttl-duration, if non-zero, defines the maximum amount of time a transaction
> # can exist for in the mempool.
> #
> # Note, if ttl-num-blocks is also defined, a transaction will be removed if it
> # has existed in the mempool at least ttl-num-blocks number of blocks or if it's
> # insertion time into the mempool is beyond ttl-duration.
> ttl-duration = "0s"
> 
> # ttl-num-blocks, if non-zero, defines the maximum number of blocks a transaction
> # can exist for in the mempool.
> #
> # Note, if ttl-duration is also defined, a transaction will be removed if it
> # has existed in the mempool at least ttl-num-blocks number of blocks or if
> # it's insertion time into the mempool is beyond ttl-duration.
> ttl-num-blocks = 0
> 
365a414,423
> ###         Storage Configuration Options           ###
> #######################################################
> 
> # Set to true to discard ABCI responses from the state store, which can save a
> # considerable amount of disk space. Set to false to ensure ABCI responses are
> # persisted. ABCI responses are required for /block_results RPC queries, and to
> # reindex events in the command-line tool.
> discard_abci_responses = false
> 
> #######################################################
378a437,438
> #   3) "psql" - the indexer services backed by PostgreSQL.
> # When "kv" or "psql" is chosen "tx.height" and "tx.hash" will always be indexed.
379a440,443
> 
> # The PostgreSQL connection configuration, the connection format:
> #   postgresql://<user>:<password>@<host>:<port>/<db>?<opts>
> psql-conn = ""
